default:
  image: node:latest
  before_script:
    - npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

stages:
  - test
  - build
  - release

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

"Eslint Validations":
  stage: test
  script:
    - npm run lint

"Tests":
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm run test:unit

"Build Library":
  stage: build
  artifacts:
    paths:
      - dist/
    expire_in: 1 month
  dependencies:
    - "Tests"
    - "Eslint Validations"
  script:
    - npm run build

"Publish Pre-release Library":
  stage: release
  dependencies:
    - "Build Library"
  script:
    - npm run semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "beta" || $CI_COMMIT_BRANCH == "alpha"

"Publish Stable Library":
  stage: release
  dependencies:
    - "Build Library"
  script:
    - npm run semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
